[package]
name = "bad64"
version = "0.1.0"
authors = ["yrp <yrp604@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bad64-sys = { path = "../bad64-sys" }
cstr_core = "0.2"
